### ISSUE TITLE
Question: General templates in this repo?

### ISSUE THREAD

**Issue by awwad** [secure-systems-lab/sample-documents#1]
Is this repository a good place for general project templates for the lab? For example, .pyup.yml, .travis.yml...?

**Comment by vladimir-v-diaz** [comment]
Sure, I don't see a problem with storing all our project templates here.

**Comment by vladimir-v-diaz** [comment]
I edited the repository description so it's clear that general project templates for the lab are stored here, and not just GitHub templates.
